#====================================================================================================================================
# Network System.
#====================================================================================================================================

[network]

# Dump all VNetwork packets.
dump_packets = false

# Use specified DNS server.
dns = "8.8.8.8"
